# Read the Docs configuration file for veldist
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    post_install:
      # Install the package itself so autodoc can import it
      - pip install .

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

# Explicitly set the version of the Sphinx builder
formats:
  - pdf
  - epub

# Install Python dependencies required to build your docs
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
